"""Initial migration.

Revision ID: 46274abfa31e
Revises: 791dfbff47aa
Create Date: 2024-12-03 16:59:41.503415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46274abfa31e'
down_revision = '791dfbff47aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
